- name: Create an instance
  hosts: localhost
  vars:
      gcp_project: "silicon-synapse-324912"
      gcp_cred_kind: serviceaccount
      gcp_cred_file: "silicon-synapse-324912-37090482e198.json"
      zone: "us-central1-a"
      region: "us-central1"

  tasks:
  - name: create a disk
    gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 20
         source_image: "projects/rhel-cloud/global/images/rhel-8-v20211214"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
    register: disk

  - name: create a address
    gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
    register: address

  - name: create a instance
    gcp_compute_instance:
         state: present
         name: k8s-worker-gcp
         machine_type: e2-small
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
           - network:
             access_configs:
             - name: 'External NAT'
               nat_ip: "{{ address }}"
               type: 'ONE_TO_ONE_NAT'
         metadata:
           managed-by: "Ansible"
           ssh-keys: ":\n"    
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
    register: instance

  - name: Wait for SSH to come up
    wait_for: host={{ address.address }} port=22 delay=10 timeout=60
